services:
  database:
    container_name: database
    image: postgres:17
    environment:
      POSTGRES_DB: linkty
      POSTGRES_USER: linkty
      POSTGRES_PASSWORD: linkty
    ports:
      - "5432:5432"
    volumes:
      - db-linkty-data:/var/lib/postgresql/data
    restart: always

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: linkty-api/target/linkty-api-1.0.0-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/linkty
      SPRING_DATASOURCE_USERNAME: linkty
      SPRING_DATASOURCE_PASSWORD: linkty
      LINK_EXPIRED: 7
    ports:
      - '8080:8080'
    depends_on:
      - database
    restart: always

  front:
    container_name: front
    build: ./linkty-front
    ports:
      - '4200:4200'
    depends_on:
      - api
    restart: always

volumes:
  db-linkty-data: